version: "3.8"

services:
  mc:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.20.1
      FABRIC_VERSION: 0.14.22
      ONLINE_MODE: "FALSE"
      WORLD: http://144.24.141.160:8090/25703324257425422431383416/AgAD6QsA/world.zip
volumes:
  fabric:
